### PR TITLE
Update zh_CN.lang by Number_Sir

### PR DESCRIPTION
**Pull request by ChirenCQR**
Update zh_CN.lang by Number_Sir

### CODE REVIEW

**Comment by WuzgXY-GitHub** [comment]
As Number_Sir has become the localizer of LotR Mod and changed a lot, he has made this fit the translation of LotR Mod itself.

**Comment by WuzgXY-GitHub** [comment]
@ChirenCQR Please convert this into a draft, this text is not completely correct, and I'm going to make a review.

**Comment by ChirenCQR** [comment]
> @ChirenCQR Please convert this into a draft, this text is not completely correct, and I'm going to make a review.

You can get it in our QQ group. NumberSir sent it to QQ group last night.

**Comment by ChirenCQR** [comment]
> @ChirenCQR Please convert this into a draft, this text is not completely correct, and I'm going to make a review.

And you can send to me if you have any question by QQ or Wechat in Chinese，because my English is poor. QwQ~

**Comment by WuzgXY-GitHub** [comment]
> QwQ

Try not to use QwQ as an emoji because it is from Furry while in Chinese it has no meaning of Furry xP

**Comment by ChirenCQR** [comment]
> > QwQ
> 
> Try not to use QwQ as an emoji because it is from Furry while in Chinese it has no meaning of Furry xP

Emm，these words you can talk to me in private by QQ, thanks.

**Pull request merged**
